### ISSUE TITLE
lack of installation instructions

### ISSUE THREAD

**Issue by whitj00** [mappum/mercury#3]
Please include an INSTALL.md or COMPILE.md in order to make it easier to compile yourself without trusting a jar or having to decompile it

**Comment by mappum** [comment]
I set up the project to easily build with Maven, and some simple instructions in the README. 4a140487409a2029704bcfc135b2d797bc07534c

@whitj00 Could you try it out to make sure it builds for you? I've only tested the build process on my own machine so I'm not sure if it will go smoothly everywhere.
