### ISSUE TITLE
Client does not prevent creating multiple orders on same coins

### ISSUE THREAD

**Issue by ssa3512** [mappum/mercury#4]
In the mercury alpha client, you can create multiple orders using the same coins. For example, with 1000 DOGE in my wallet, I was able to create two sell orders totaling 2000 DOGE @ 0.00000052 BTC for a total of 0.00104 BTC

![mercury](https://cloud.githubusercontent.com/assets/1991399/6530419/c377cb1e-c3fe-11e4-9c6d-1e0e7c9500aa.png)

**Comment by mappum** [comment]
Thanks for reporting this. This was actually fixed recently (
6bdb58417dbeaabfa479c23e34e4c8b815dd7fe5), but now the download version is
slightly out of date. I'll update the download soon when this version is
ready for release.
